{{- if eq .Values.tls.enabled true }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.tls.default_issuer_name }}
spec:
  acme:
    server: {{ .Values.tls.server }}
    email: {{ .Values.tls.acme_registration_email }}
    privateKeySecretRef:
      name: {{ template "fn.tls_secret_name" . }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.className | default "nginx" }}
{{- end -}}
